### ISSUE TITLE
__attribute__((constructor, used)) doesn't work if build with static lib of odp-dpdk

### ISSUE THREAD

**Issue by lvsgate** [OpenDataPlane/odp-dpdk#15] opened 2018-01-31 02:03 UTC
odp-dpdk version: 1.15.0.0_DPDK_17.02
1. configure --disable-shared for odp-dpdk and build
2. build ofp with  odp-dpdk
3. run any example app of ofp and got the result
`"odp_packet_dpdk.c:162:setup_pkt_dpdk():No driver found for interface: 0"`
4. It seems that `RTE_PMD_REGISTER_PCI(net_ixgbe, rte_ixgbe_pmd.pci_drv) `only be called in shared library

**Comment by matiaselo** [comment] 2018-02-06 11:16
This happens also with odp-linux when using DPDK pktio. This is likely caused by OFP not properly importing flags from libodp-linux.pc/libodp-dpdk.pc. I'm in the middle of porting patches from odp-linux to bring odp-dpdk up to date, but setting "PKG_CONFIG="pkg-config --static"" environment variable fixed driver linking with odp-linux.

**Comment by lumag** [comment] 2018-02-27 10:15
`pkg-config --static` should only be necessary if one is building static app. It is needed to satisfy linking.
@matiaselo Could you please provide minimal example that we can use to verify static linking with ODP/DPDK (in odp-linux case).

**Comment by lumag** [comment] 2018-02-27 11:25
Regarding odp-dpdk. I remember doing several iterations with odp-linux/dpdk till I was able to fix possible app.odp/dpdk linking cases.

**Comment by matiaselo** [comment] 2018-02-28 13:59
@lumag I assumed OFP  was built  is static as ODP was build with '--disable-shared'. 

I've used OFP's fpm_burstmode example to verify driver linking. E.g.
`./fpm_burstmode -i 0,1 -c 1`

**Comment by matiaselo** [comment] 2019-08-23 10:26
Fixed by #79.

**Closed by matiaselo** 2019-08-23 10:26 UTC
